apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fastapi-prod
  region: eu-west-3
  version: "1.29"

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 30
    ssh:
      allow: true
      publicKeyName: fastapi-key
