apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "auth.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: {{ include "auth.fullname" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: microservices-platform-dev-app-secrets
        property: SECRET_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: microservices-platform-dev-app-secrets
        property: DATABASE_URL