pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
    - cat
    tty: true
  - name: helm
    image: alpine/helm:3.14.0
    command:
    - cat
    tty: true
"""
    }
  }

  environment {
    DOCKERHUB_USER = "titi92390"
    REGISTRY = "docker.io"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Images') {
      steps {
        container('kaniko') {
          script {
            def services = ["auth", "users", "items"]

            for (svc in services) {
              sh """
              /kaniko/executor \
                --context ./Microservices/${svc} \
                --dockerfile ./Microservices/${svc}/Dockerfile \
                --destination=${REGISTRY}/${DOCKERHUB_USER}/${svc}:dev
              """
            }
          }
        }
      }
    }

    stage('Deploy to Kubernetes (Helm)') {
      steps {
        container('helm') {
          sh """
            helm upgrade --install platform helm/platform \
              -n fastapi \
              --create-namespace
          """
        }
      }
    }
  }

  post {
    success {
      echo "✅ CI/CD terminé : images + déploiement OK"
    }
    failure {
      echo "❌ Pipeline échoué"
    }
  }
}
