pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                cd Microservices/items
                python3 -m venv .venv
                . .venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest httpx
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                cd Microservices/items
                . .venv/bin/activate
                pytest -v
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Tests automatisés OK – pipeline validée"
        }
        failure {
            echo "❌ Tests en échec – pipeline stoppée"
        }
    }
}
