apiVersion: v1
kind: Secret
metadata:
  name: {{ include "users.fullname" . }}-secret
  labels:
    {{ include "users.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: "my-secret-key-for-dev"
