apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-secret
  labels:
    {{ include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: "my-secret-key-for-dev"
