global:
  useExternalSecrets: false
  database:
    host: postgres-postgresql.dev.svc.cluster.local
    port: "5432"
    name: postgres
    user: postgres
    password: postgres

auth:
  enabled: true
  replicaCount: 1
  image:
    repository: titi92390/auth
    tag: dev
    pullPolicy: Always
  env:
    APP_ENV: dev
  resources: {}

users:
  enabled: true
  replicaCount: 1
  image:
    repository: titi92390/users
    tag: dev
    pullPolicy: Always
  env:
    APP_ENV: dev
  resources: {}

items:
  enabled: true
  replicaCount: 1
  image:
    repository: titi92390/items
    tag: dev
    pullPolicy: Always
  env:
    APP_ENV: dev
  resources: {}

frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: titi92390/frontend
    registry: docker.io
    tag: dev
    pullPolicy: Always
  env:
    NEXT_PUBLIC_API_BASE: "http://172.31.31.104"
  service:
    port: 3000
